### ISSUE TITLE
Errors with malformed CSS

### ISSUE THREAD

**Issue by Synchro** [MyIntervals/emogrifier#179]
I ran into two errors when processing some malformed style tags.

The style tag contained some stray HTML injected by ckeditor:

``` css
table.columns .right-text-pad {
  padding-right: 10px;
}
<style data-cke-temp="1">html{cursor:text;*cursor:auto}
img,input,textarea{cursor:default}
```

Trying to process this produced two errors. The first is caused by it choosing `<style data-cke-temp="1">html` as a selector, which will not convert to a valid xpath query:

```
2015-06-19 14:02:03 DOMXPath::query(): Invalid expression (error type 2 in ./vendor/pelago/emogrifier/Classes/Emogrifier.php on line 279)
```

The second is a consequence of this, attempting to iterate over the failed result of the query because the return value is not checked:

```
2015-06-19 14:02:03 Invalid argument supplied for foreach() (error type 2 in ./vendor/pelago/emogrifier/Classes/Emogrifier.php on line 282)
```

Obviously it would be better if bad CSS was not passed in in the first place, but it would be better to ignore it than throw errors.
