### ISSUE TITLE
Fatal error: Uncaught RuntimeException: DOMXPath::query():

### ISSUE THREAD

**Issue by nikmauro** [MyIntervals/emogrifier#439]
Fatal error: Uncaught RuntimeException: DOMXPath::query(): Invalid expression in /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 1108 in /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php:1785 Stack trace: #0 [internal function]: Pelago\Emogrifier->handleXpathQueryWarnings(2, 'DOMXPath::query...', '/var/www/vhosts...', 1108, Array) #1 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(1108): DOMXPath->query('//*[contains(co...') #2 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(1063): Pelago\Emogrifier->existsMatchForCssSelector(Object(DOMXPath), '.mobile_link a[...') #3 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(412): Pelago\Emogrifier->copyCssWithMediaToStyleNode(Object(DOMDocument), Object(DOMXPath), '@media screen a...') #4 /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php(328): Pelago\Em in /var/www/vhosts/.com/httpdocs/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 1785

```CSS

a[href^="tel"], a[href^="sms"] {
                text-decoration: none;
                color: black; /* or whatever your want */
                pointer-events: none;
                cursor: default;
            }

            .mobile_link a[href^="tel"], .mobile_link a[href^="sms"] {
                text-decoration: default;
                color: orange !important; /* or whatever your want */
                pointer-events: auto;
                cursor: default;
            }

 @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
            a[href^="tel"], a[href^="sms"] {
                text-decoration: none;
                color: blue; /* or whatever your want */
                pointer-events: none;
                cursor: default;
            }
```
